# Application Details
spring.application.name=library-management-system

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/library_management_system?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Token Configuration
# Strong 256-bit / 512-bit HS512 signing secret key (64 characters/bytes minimum)
app.jwt.secret=9a6747fc6259aa4f072417621b6238b74801f21dbcd5cf9573887019808a7981f4a13247bb411ec5a4b7f7e914041b694b8e2cb32470ab7f29a0081d567789a2
# 15 Minutes Expiration for Access Token (in milliseconds)
app.jwt.expiration-ms=900000
# 7 Days Expiration for Refresh Token (in milliseconds)
app.jwt.refresh-expiration-ms=604800000
